# -*- coding: utf-8 -*-

import torch
from PIL import Image
from transformers import AutoProcessor, LlavaForConditionalGeneration
from peft import PeftModel
from src.perception_module.prompt_utils import format_inference_prompt

class VLMInferenceHandler:
    """
    A handler class for performing inference with the fine-tuned LLaVA model.

    This class loads the base model and the trained LoRA adapters, providing a simple
    interface to get structured predictions from an image and a text query.
    """
    def __init__(self, base_model_id: str, adapter_path: str, use_4bit: bool = True):
        """
        Initializes the inference handler.

        Args:
            base_model_id (str): The model identifier of the base LLaVA model.
            adapter_path (str): Path to the directory containing the saved LoRA adapters.
            use_4bit (bool): Whether to load the base model with 4-bit quantization.
        """
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"Initializing VLMInferenceHandler on device: {self.device}")
        
        # Load the processor
        self.processor = AutoProcessor.from_pretrained(base_model_id, trust_remote_code=True)

        # Load the base model with quantization if specified
        bnb_config = None
        if use_4bit:
            bnb_config = torch.quantization.BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_compute_dtype=torch.float16
            )
        
        base_model = LlavaForConditionalGeneration.from_pretrained(
            base_model_id,
            torch_dtype=torch.float16,
            quantization_config=bnb_config,
            low_cpu_mem_usage=True,
            trust_remote_code=True
        )
        
        # Load the LoRA adapters and merge them into the model
        print(f"Loading LoRA adapters from: {adapter_path}")
        self.model = PeftModel.from_pretrained(base_model, adapter_path)
        # For faster inference, you can optionally merge and unload the adapters
        # self.model = self.model.merge_and_unload()
        self.model.to(self.device)
        print("Model and adapters loaded successfully.")

    @torch.inference_mode()
    def predict(self, image_path: str, text_query: str) -> str:
        """
        Performs inference on a single image and text query.

        Args:
            image_path (str): Path to the input engineering drawing.
            text_query (str): The natural language query from the user.

        Returns:
            str: The structured text output generated by the model.
        """
        try:
            image = Image.open(image_path).convert("RGB")
        except FileNotFoundError:
            return "Error: Image file not found."

        # Format the prompt using the utility function
        prompt = format_inference_prompt(text_query)
        
        inputs = self.processor(
            text=prompt, images=image, return_tensors="pt"
        ).to(self.device)

        print("Generating response...")
        # Generate output
        output = self.model.generate(**inputs, max_new_tokens=512, do_sample=False)
        
        # Decode the output and clean up the prompt part
        response = self.processor.decode(output[0], skip_special_tokens=True)
        
        # The response includes the prompt, so we extract only the assistant's part
        assistant_tag = "ASSISTANT:"
        assistant_response = response.split(assistant_tag)[-1].strip()
        
        return assistant_response

if __name__ == '__main__':
    # This block demonstrates how to use the VLMInferenceHandler.
    # To run this, you need a trained model adapter and an image.
    # Example usage (placeholders, replace with actual paths):
    # python src/perception_module/inference.py \
    #   --base_model "llava-hf/llava-1.5-7b-hf" \
    #   --adapter_path "trained_models/stage1_llava_finetuned/final_checkpoint" \
    #   --image_path "data/end_to_end_testset/cases/case_01/drawing.jpg" \
    #   --query "请为这张图纸中的零件规划加工工艺。"

    import argparse
    parser = argparse.ArgumentParser(description="Run inference with the fine-tuned LLaVA model.")
    parser.add_argument("--base_model", type=str, required=True, help="Base model ID from Hugging Face.")
    parser.add_argument("--adapter_path", type=str, required=True, help="Path to the trained LoRA adapters.")
    parser.add_argument("--image_path", type=str, required=True, help="Path to the input image.")
    parser.add_argument("--query", type=str, required=True, help="The text query.")
    
    args = parser.parse_args()

    handler = VLMInferenceHandler(base_model_id=args.base_model, adapter_path=args.adapter_path)
    result = handler.predict(image_path=args.image_path, text_query=args.query)
    
    print("\n--- Model Prediction ---")
    print(result)