# -*- coding: utf-8 -*-

def format_inference_prompt(user_query: str) -> str:
    """
    Formats the user query into the specific prompt structure required by the LLaVA model
    for inference.

    The model was trained on a specific chat template. To get the best results,
    inference prompts must follow the same structure. The template typically looks like:
    "USER: <image>\n{question} ASSISTANT:"

    Args:
        user_query (str): The raw natural language query from the user.

    Returns:
        str: A formatted string ready to be passed to the model's processor.
    """
    if not isinstance(user_query, str) or not user_query:
        raise ValueError("User query must be a non-empty string.")

    # The <image> token is a special placeholder that the LLaVA processor understands.
    # It signals where the image features should be inserted in the token sequence.
    # We append "ASSISTANT:" to signal the model that it should start generating its response.
    prompt = f"USER: <image>\n{user_query.strip()} ASSISTANT:"
    
    return prompt

def parse_structured_output(model_output: str) -> dict:
    """
    Parses the structured string output from the model into a Python dictionary.

    The model is trained to output a specific format, e.g.:
    "意图: ...\n实体: [...]\n知识: ..."

    This function robustly extracts these fields.

    Args:
        model_output (str): The raw string generated by the model.

    Returns:
        dict: A dictionary with keys 'intent', 'entities', and 'knowledge'.
              Returns a dictionary with error messages if parsing fails.
    """
    parsed_data = {
        'intent': None,
        'entities': [],
        'knowledge': None,
        'error': None
    }

    if not model_output or not isinstance(model_output, str):
        parsed_data['error'] = "Input is not a valid string."
        return parsed_data

    try:
        # Normalize line breaks and split into lines
        lines = model_output.strip().replace('\\n', '\n').split('\n')
        
        current_key = None
        temp_buffer = {}

        for line in lines:
            line = line.strip()
            if not line:
                continue

            if line.startswith("意图:"):
                current_key = 'intent'
                temp_buffer[current_key] = line[len("意图:"):].strip()
            elif line.startswith("实体:"):
                current_key = 'entities'
                # Extract content within brackets, e.g., "[...]"
                entities_str = line[line.find('[')+1 : line.rfind(']')]
                # Split by comma and strip whitespace
                temp_buffer[current_key] = [e.strip() for e in entities_str.split(',') if e.strip()]
            elif line.startswith("知识:"):
                current_key = 'knowledge'
                temp_buffer[current_key] = line[len("知识:"):].strip()
            elif current_key:
                # This handles multi-line values, especially for 'knowledge'
                if isinstance(temp_buffer[current_key], str):
                    temp_buffer[current_key] += " " + line

        parsed_data.update(temp_buffer)
        if not all([parsed_data.get('intent'), parsed_data.get('entities')]):
             parsed_data['error'] = "Could not find all required keys ('意图', '实体')."

    except Exception as e:
        parsed_data['error'] = f"An unexpected error occurred during parsing: {str(e)}"
        parsed_data['raw_output'] = model_output # Keep raw output for debugging

    return parsed_data

if __name__ == '__main__':
    # --- Test format_inference_prompt ---
    print("--- Testing prompt formatting ---")
    query = "请为这个零件制定工艺。"
    formatted = format_inference_prompt(query)
    print(f"Input: '{query}'")
    print(f"Formatted: '{formatted}'")
    assert formatted == "USER: <image>\n请为这个零件制定工艺。 ASSISTANT:"
    print("Formatting test passed.\n")

    # --- Test parse_structured_output ---
    print("--- Testing output parsing ---")
    good_output = "意图: 为该齿轮轴制定加工计划。\n实体: [零件名称: 齿轮轴, 材料: 45钢, 关键工艺: 粗车]\n知识: 这是一个测试知识点。"
    bad_output_1 = "这是一个不规范的输出"
    bad_output_2 = "意图: 有意图但没有实体"
    
    parsed_good = parse_structured_output(good_output)
    print(f"Input:\n{good_output}\nParsed:\n{parsed_good}\n")
    assert parsed_good['intent'] == "为该齿轮轴制定加工计划。"
    assert parsed_good['entities'] == ["零件名称: 齿轮轴", "材料: 45钢", "关键工艺: 粗车"]
    
    parsed_bad_1 = parse_structured_output(bad_output_1)
    print(f"Input:\n{bad_output_1}\nParsed:\n{parsed_bad_1}\n")
    assert parsed_bad_1['error'] is not None

    parsed_bad_2 = parse_structured_output(bad_output_2)
    print(f"Input:\n{bad_output_2}\nParsed:\n{parsed_bad_2}\n")
    assert parsed_bad_2['error'] is not None

    print("Parsing tests passed.")