# -*- coding: utf-8 -*-

"""
src.utils.metrics - End-to-End Evaluation Metrics.

This module implements the custom evaluation metrics as described in the paper:
1.  Sequence Accuracy (SeqAcc): Based on normalized Levenshtein distance to
    measure the correctness of the generated process sequence.
2.  Key Parameter Acceptability (KPA): Measures the technical soundness of the
    recommended machining parameters.
"""

from typing import List, Dict, Any

def _levenshtein_distance(seq1: List[Any], seq2: List[Any]) -> int:
    """
    Calculates the Levenshtein distance between two sequences.
    A helper function for Sequence Accuracy.
    """
    m, n = len(seq1), len(seq2)
    
    # Initialize DP table
    dp = [[0] * (n + 1) for _ in range(m + 1)]
    for i in range(m + 1):
        dp[i][0] = i
    for j in range(n + 1):
        dp[0][j] = j

    # Fill DP table
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            cost = 0 if seq1[i - 1] == seq2[j - 1] else 1
            dp[i][j] = min(dp[i - 1][j] + 1,        # Deletion
                           dp[i][j - 1] + 1,        # Insertion
                           dp[i - 1][j - 1] + cost) # Substitution
    
    return dp[m][n]

def calculate_sequence_accuracy(predicted_sequence: List[str], ground_truth_sequence: List[str]) -> float:
    """
    Calculates the Sequence Accuracy (SeqAcc) based on normalized Levenshtein distance.

    Formula: SeqAcc = 1 - (LevenshteinDistance / max(len(pred), len(truth)))

    Args:
        predicted_sequence (List[str]): The process sequence generated by the model.
        ground_truth_sequence (List[str]): The correct process sequence.

    Returns:
        float: The Sequence Accuracy score, ranging from 0.0 to 1.0.
    """
    len_pred = len(predicted_sequence)
    len_truth = len(ground_truth_sequence)

    if len_pred == 0 and len_truth == 0:
        return 1.0

    max_len = max(len_pred, len_truth)
    if max_len == 0:
        return 1.0 # Should be covered by the case above, but as a safeguard.

    distance = _levenshtein_distance(predicted_sequence, ground_truth_sequence)
    
    accuracy = 1.0 - (distance / max_len)
    
    return accuracy

def calculate_key_parameter_acceptability(
    predicted_parameters: Dict[str, Dict[str, Any]], 
    ground_truth_parameters: Dict[str, Dict[str, Any]]
) -> float:
    """
    Calculates the Key Parameter Acceptability (KPA).

    This metric computes the ratio of predicted parameters that fall within the
    acceptable range defined in the ground truth.

    Args:
        predicted_parameters (Dict): The parameters generated by the model.
            Example: {"rough_turning": {"spindle_speed_rpm": 750}}
        ground_truth_parameters (Dict): The ground truth with acceptable ranges.
            Example: {"rough_turning": {"spindle_speed_rpm": [600, 900]}}

    Returns:
        float: The KPA score, ranging from 0.0 to 1.0.
    """
    total_params_evaluated = 0
    acceptable_params_count = 0

    # Iterate through each process step in the ground truth
    for process, params_gt in ground_truth_parameters.items():
        if process not in predicted_parameters:
            continue

        params_pred = predicted_parameters[process]
        
        # Iterate through each parameter for that process
        for param_name, gt_value in params_gt.items():
            if param_name not in params_pred:
                continue

            total_params_evaluated += 1
            pred_value = params_pred[param_name]
            
            is_acceptable = False
            # Case 1: Ground truth is a numeric range [min, max]
            if isinstance(gt_value, list) and len(gt_value) == 2 and all(isinstance(v, (int, float)) for v in gt_value):
                if isinstance(pred_value, (int, float)) and gt_value[0] <= pred_value <= gt_value[1]:
                    is_acceptable = True
            # Case 2: Ground truth is a list of acceptable string values
            elif isinstance(gt_value, list) and all(isinstance(v, str) for v in gt_value):
                if isinstance(pred_value, str) and pred_value in gt_value:
                    is_acceptable = True

            if is_acceptable:
                acceptable_params_count += 1

    if total_params_evaluated == 0:
        # If no common parameters were found to evaluate, we can't claim any accuracy.
        # Alternatively, could be 1.0 if the prediction was not expected to produce params.
        # Returning 0.0 is a stricter, safer default.
        return 0.0

    kpa_score = acceptable_params_count / total_params_evaluated
    
    return kpa_score